# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions

default_platform(:ios)

platform :ios do
  desc "Upload a signed .ipa to TestFlight using an App Store Connect API key"
  lane :upload_testflight do |options|
    api_key = app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_content: ENV["ASC_KEY_CONTENT"],
      is_key_content_base64: true,
    )

    upload_to_testflight(
      api_key: api_key,
      ipa: options[:ipa_path],
      skip_waiting_for_build_processing: true,
      skip_submission: true,
    )
  end
end
